language: r
cache: packages
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("adv_R_lab3")'
script:
  - Rscript -e 'devtools::check("adv_R_lab3")'
